import numpy as np


SYMPTOM_MAPPING = {
    "anxiety and nervousness": "anxiety and nervousness",
    "depression": "depression",
    "shortness of breath": "shortness of breath",
    "depressive or psychotic symptoms": "depressive or psychotic symptoms",
    "sharp chest pain": "sharp chest pain",
    "dizziness": "dizziness",
    "insomnia": "insomnia",
    "abnormal involuntary movements": "abnormal involuntary movements",
    "chest tightness": "chest tightness",
    "palpitations": "palpitations",
    "irregular heartbeat": "irregular heartbeat",
    "breathing fast": "breathing fast",
    "hoarse voice": "hoarse voice",
    "sore throat": "sore throat",
    "difficulty speaking": "difficulty speaking",
    "cough": "cough",
    "nasal congestion": "nasal congestion",
    "throat swelling": "throat swelling",
    "diminished hearing": "diminished hearing",
    "difficulty in swallowing": "difficulty in swallowing",
    "skin swelling": "skin swelling",
    "retention of urine": "retention of urine",
    "leg pain": "leg pain",
    "hip pain": "hip pain",
    "suprapubic pain": "suprapubic pain",
    "blood in stool": "blood in stool",
    "lack of growth": "lack of growth",
    "symptoms of the scrotum and testes": "symptoms of the scrotum and testes",
    "swelling of scrotum": "swelling of scrotum",
    "pain in testicles": "pain in testicles",
    "pus draining from ear": "pus draining from ear",
    "jaundice": "jaundice",
    "white discharge from eye": "white discharge from eye",
    "irritable infant": "irritable infant",
    "abusing alcohol": "abusing alcohol",
    "fainting": "fainting",
    "hostile behavior": "hostile behavior",
    "drug abuse": "drug abuse",
    "sharp abdominal pain": "sharp abdominal pain",
    "feeling ill": "feeling ill",
    "vomiting": "vomiting",
    "headache": "headache",
    "nausea": "nausea",
    "diarrhea": "diarrhea",
    "vaginal itching": "vaginal itching",
    "painful urination": "painful urination",
    "involuntary urination": "involuntary urination",
    "pain during intercourse": "pain during intercourse",
    "frequent urination": "frequent urination",
    "lower abdominal pain": "lower abdominal pain",
    "vaginal discharge": "vaginal discharge",
    "blood in urine": "blood in urine",
    "hot flashes": "hot flashes",
    "intermenstrual bleeding": "intermenstrual bleeding",
    "hand or finger pain": "hand or finger pain",
    "wrist pain": "wrist pain",
    "hand or finger swelling": "hand or finger swelling",
    "arm pain": "arm pain",
    "wrist swelling": "wrist swelling",
    "arm stiffness or tightness": "arm stiffness or tightness",
    "arm swelling": "arm swelling",
    "hand or finger stiffness or tightness": "hand or finger stiffness or tightness",
    "lip swelling": "lip swelling",
    "toothache": "toothache",
    "abnormal appearing skin": "abnormal appearing skin",
    "skin lesion": "skin lesion",
    "acne or pimples": "acne or pimples",
    "facial pain": "facial pain",
    "mouth ulcer": "mouth ulcer",
    "skin growth": "skin growth",
    "diminished vision": "diminished vision",
    "double vision": "double vision",
    "symptoms of eye": "symptoms of eye",
    "pain in eye": "pain in eye",
    "abnormal movement of eyelid": "abnormal movement of eyelid",
    "foreign body sensation in eye": "foreign body sensation in eye",
    "irregular appearing scalp": "irregular appearing scalp",
    "back pain": "back pain",
    "neck pain": "neck pain",
    "low back pain": "low back pain",
    "pain of the anus": "pain of the anus",
    "pain during pregnancy": "pain during pregnancy",
    "pelvic pain": "pelvic pain",
    "impotence": "impotence",
    "vomiting blood": "vomiting blood",
    "regurgitation": "regurgitation",
    "burning abdominal pain": "burning abdominal pain",
    "restlessness": "restlessness",
    "wheezing": "wheezing",
    "peripheral edema": "peripheral edema",
    "neck mass": "neck mass",
    "ear pain": "ear pain",
    "jaw swelling": "jaw swelling",
    "mouth dryness": "mouth dryness",
    "neck swelling": "neck swelling",
    "knee pain": "knee pain",
    "foot or toe pain": "foot or toe pain",
    "ankle pain": "ankle pain",
    "bones are painful": "bones are painful",
    "elbow pain": "elbow pain",
    "knee swelling": "knee swelling",
    "skin moles": "skin moles",
    "weight gain": "weight gain",
    "problems with movement": "problems with movement",
    "knee stiffness or tightness": "knee stiffness or tightness",
    "leg swelling": "leg swelling",
    "foot or toe swelling": "foot or toe swelling",
    "heartburn": "heartburn",
    "infant feeding problem": "infant feeding problem",
    "vaginal pain": "vaginal pain",
    "vaginal redness": "vaginal redness",
    "weakness": "weakness",
    "decreased heart rate": "decreased heart rate",
    "increased heart rate": "increased heart rate",
    "ringing in ear": "ringing in ear",
    "plugged feeling in ear": "plugged feeling in ear",
    "itchy ear(s)": "itchy ear(s)",
    "frontal headache": "frontal headache",
    "fluid in ear": "fluid in ear",
    "spots or clouds in vision": "spots or clouds in vision",
    "eye redness": "eye redness",
    "lacrimation": "lacrimation",
    "itchiness of eye": "itchiness of eye",
    "blindness": "blindness",
    "eye burns or stings": "eye burns or stings",
    "decreased appetite": "decreased appetite",
    "excessive anger": "excessive anger",
    "loss of sensation": "loss of sensation",
    "focal weakness": "focal weakness",
    "symptoms of the face": "symptoms of the face",
    "disturbance of memory": "disturbance of memory",
    "paresthesia": "paresthesia",
    "side pain": "side pain",
    "fever": "fever",
    "shoulder pain": "shoulder pain",
    "shoulder stiffness or tightness": "shoulder stiffness or tightness",
    "ache all over": "ache all over",
    "lower body pain": "lower body pain",
    "problems during pregnancy": "problems during pregnancy",
    "spotting or bleeding during pregnancy": "spotting or bleeding during pregnancy",
    "cramps and spasms": "cramps and spasms",
    "upper abdominal pain": "upper abdominal pain",
    "stomach bloating": "stomach bloating",
    "changes in stool appearance": "changes in stool appearance",
    "unusual color or odor to urine": "unusual color or odor to urine",
    "kidney mass": "kidney mass",
    "symptoms of prostate": "symptoms of prostate",
    "difficulty breathing": "difficulty breathing",
    "rib pain": "rib pain",
    "joint pain": "joint pain",
    "hand or finger lump or mass": "hand or finger lump or mass",
    "chills": "chills",
    "groin pain": "groin pain",
    "fatigue": "fatigue",
    "regurgitation.1": "regurgitation",
    "symptoms of the kidneys": "symptoms of the kidneys",
    "melena": "melena",
    "coughing up sputum": "coughing up sputum",
    "seizures": "seizures",
    "delusions or hallucinations": "delusions or hallucinations",
    "excessive urination at night": "excessive urination at night",
    "bleeding from eye": "bleeding from eye",
    "rectal bleeding": "rectal bleeding",
    "constipation": "constipation",
    "temper problems": "temper problems",
    "coryza": "coryza",
    "hemoptysis": "hemoptysis",
    "allergic reaction": "allergic reaction",
    "congestion in chest": "congestion in chest",
    "sleepiness": "sleepiness",
    "apnea": "apnea",
    "abnormal breathing sounds": "abnormal breathing sounds",
    "blood clots during menstrual periods": "blood clots during menstrual periods",
    "pulling at ears": "pulling at ears",
    "gum pain": "gum pain",
    "redness in ear": "redness in ear",
    "fluid retention": "fluid retention",
    "flu-like syndrome": "flu-like syndrome",
    "sinus congestion": "sinus congestion",
    "painful sinuses": "painful sinuses",
    "fears and phobias": "fears and phobias",
    "recent pregnancy": "recent pregnancy",
    "uterine contractions": "uterine contractions",
    "burning chest pain": "burning chest pain",
    "back cramps or spasms": "back cramps or spasms",
    "back mass or lump": "back mass or lump",
    "nosebleed": "nosebleed",
    "long menstrual periods": "long menstrual periods",
    "heavy menstrual flow": "heavy menstrual flow",
    "unpredictable menstruation": "unpredictable menstruation",
    "painful menstruation": "painful menstruation",
    "infertility": "infertility",
    "frequent menstruation": "frequent menstruation",
    "sweating": "sweating"
};


# =====================================================
# NORMALIZE SYMPTOMS
# =====================================================


def normalize_symptom(symptom):

    symptom = str(symptom).strip().lower()

    if symptom in SYMPTOM_MAPPING:
        symptom = SYMPTOM_MAPPING[symptom]

    return symptom


# =====================================================
# PREDICT DISEASE
# =====================================================


def predict_disease(
    user_symptoms,
    feature_columns,
    ann_model,
    label_encoder
):

    input_vector = np.zeros(len(feature_columns))

    matched_symptoms = []
    unmatched_symptoms = []
    return disease_name, confidence